version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ask_e9y_db
    ports:
      - "5433:5432"  # Different port to avoid conflicts with local Postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./db/sample_data.sql:/docker-entrypoint-initdb.d/02-sample_data.sql
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
      - chroma_data:/app/chroma_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ask_e9y_db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEBUG=true
      - LOG_LEVEL=INFO
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  chroma_data: